//
//  MainViewController.swift
//  significant-change-location-service
//
//  Created phattarapon on 27/7/2565 BE.
//  Copyright © 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainViewController: UIViewController {

	var presenter: MainPresenterProtocol?

    @IBOutlet weak var activityNameLabel: UILabel!
    @IBOutlet weak var dateLabel: UILabel!
    @IBOutlet weak var confidentLabel: UILabel!
    @IBOutlet weak var gpsSpeedLabel: UILabel!
    @IBOutlet weak var latAndLngLabel: UILabel!
    @IBOutlet weak var locationLabel: UILabel!
    @IBOutlet weak var collectionView: UICollectionView!
    
    var activityFecthData = [ActivityForm]()
    var font = UIFont.systemFont(ofSize: 17)
    var activityData: String?
    var dateData: String?
    var confidentData: String?
    var speedData: Double?
    var latLngData: String?
    var locationData: String?
    
    override func viewDidLoad() {
        self.presenter?.notifyViewDidLoad()
        super.viewDidLoad()
        self.initUI()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
    }
    
    func initUI() {
        self.setupNavigationBar()
        let nibActivityCell = UINib(nibName: "MainCell", bundle: nil)
        self.collectionView.register(nibActivityCell, forCellWithReuseIdentifier: "MainCell")
        self.collectionView.register(UINib.init(nibName: "MainHeader", bundle: Bundle.main), forSupplementaryViewOfKind: UICollectionView.elementKindSectionHeader, withReuseIdentifier: "header")
    }
    
    func setupNavigationBar() {
        self.navigationItem.title = "Significant Change Location"
    }
}

extension MainViewController:  MainViewProtocol {
    
    //MARK: location not show and save
    func displayLocationView(location: String) {
        self.locationLabel.text = "ตำเเหน่งปัจจุบัน\n" + location
        self.locationData = location
    }
    
    func displayGpsSpeed(speed: Double) {
        self.gpsSpeedLabel.text = String(format: "ความเร็ว = %.1f", speed) + " Km/h"
        self.speedData = speed
        UserDefaults.standard.set(String(format: "%.1f", speed), forKey: "stored_speed")
    }
    
    func displayLatLng(latLng: String) {
        self.latAndLngLabel.text = "ละติจูด, ลองจิจูด\n \(latLng)"
        self.latLngData = latLng
    }
    
    func displayMotionData(date: String, activity: String) {
        self.dateLabel.text = "วันที่เริ่ม = \(date)"
        self.activityNameLabel.text = activity
        
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.2) {
            self.dateData = date
            self.activityData = activity
        }
    }
    
    func displayConfidentActivity(confident: String) {
        self.confidentLabel.text = "ความเเม่นยำ = \(confident)"
        self.confidentData = confident
    }
    
    func displayActivityFetch(activity: [ActivityForm]) {
        self.activityFecthData = activity
    }
    
    func reloadLocationNameService() {
        self.collectionView.reloadData()
    }
}

extension MainViewController: UICollectionViewDelegate, UICollectionViewDataSource {
    
    func numberOfSections(in collectionView: UICollectionView) -> Int {
        return self.activityFecthData.count
    }
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return 1
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "MainCell", for: indexPath) as! MainCell
        
        cell.displayHistoryActivity(activity: self.activityFecthData[indexPath.section])
        
        return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, at indexPath: IndexPath) -> UICollectionReusableView {
        
        let headerView = collectionView.dequeueReusableSupplementaryView(ofKind: UICollectionView.elementKindSectionHeader, withReuseIdentifier: "header", for: indexPath) as! MainHeader
        let text = "กิจกรรมที่ \(self.activityFecthData.count - indexPath.section)"
        headerView.headerLabel.text = text
        return headerView
    }
}

extension MainViewController: UICollectionViewDelegateFlowLayout {
    func collectionView(_ collectionView: UICollectionView,
                        layout collectionViewLayout: UICollectionViewLayout,
                        sizeForItemAt indexPath: IndexPath) -> CGSize {
        
        let sizeMessage: CGFloat = DynamicTextFieldSize.height(text: self.locationData, font: self.font, width: collectionView.frame.width)
        return CGSize.init(width: collectionView.frame.width, height: 180 + sizeMessage)
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, referenceSizeForHeaderInSection section: Int) -> CGSize {
        return CGSize.init(width: UIScreen.main.bounds.width, height: 30)
    }
}
