//
//  MainPresenter.swift
//  significant-change-location-service
//
//  Created phattarapon on 27/7/2565 BE.
//  Copyright © 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import CoreMotion

class MainPresenter {

    weak private var view: MainViewProtocol?
    var interactor: MainInteractorProtocol?
    private let router: MainWireframeProtocol

    init(interface: MainViewProtocol, interactor: MainInteractorProtocol?, router: MainWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension MainPresenter: MainPresenterProtocol {
    
    func notifyViewDidLoad() {
        self.interactor?.addLocationObserver()
        self.interactor?.fetchHistoryActivity()
    }
    
    func selfFetchActivity() {
        self.interactor?.fetchHistoryActivity()
    }
    
    func notifyFetchHistoryActivity(activity: [ActivityForm]) {
        self.view?.displayActivityFetch(activity: activity)
    }
    
    func notifyLocationFetched() {
        LocationHelper.shared.geoUpdate(locale: Locale.init(identifier: "th")) { (streetName) in
            self.view?.displayLocationView(location: streetName)
        }
    }
    
    func notifyDisplayGPSSpeed(speed: Double) {
        self.view?.displayGpsSpeed(speed: speed)
    }
    
    func notifyDisplayMotionData(motion: CMMotionActivity?, date: String) {
        if (motion?.stationary)! {
            print("stationary", (motion?.stationary)!)
            self.view?.displayMotionData(date: date, activity: "ไม่มีการเคลื่อนไหว")
        } else if (motion?.walking)! {
            print("walking", (motion?.walking)!)
            self.view?.displayMotionData(date: date, activity: "เดิน")
        } else if (motion?.running)! {
            print("running", (motion?.running)!)
            self.view?.displayMotionData(date: date, activity: "วิ่ง")
        } else if (motion?.automotive)! {
            print("automotive", (motion?.automotive)!)
            self.view?.displayMotionData(date: date, activity: "อยู่บนรถ")
        } else if (motion?.cycling)! {
            print("cycling", (motion?.cycling)!)
            self.view?.displayMotionData(date: date, activity: "ปั่นจักรยาน")
        }
        
        if motion?.confidence == CMMotionActivityConfidence.low {
            print("confidene = Low")
            self.view?.displayConfidentActivity(confident: "ต่ำ")
        } else if motion?.confidence == CMMotionActivityConfidence.medium {
            print("confidene = Medium")
            self.view?.displayConfidentActivity(confident: "ดี")
        } else if motion?.confidence == CMMotionActivityConfidence.high {
            print("confidene = Hight")
            self.view?.displayConfidentActivity(confident: "สูง")
        }
    }
    
    func notifyInsertHistoryActivity(activity: ActivityForm) {
        self.interactor?.insertHistoryActivity(activity: activity)
    }
}
