//
//  MainViewController.swift
//  significant-change-location-service
//
//  Created phattarapon on 27/7/2565 BE.
//  Copyright © 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainViewController: UIViewController {

	var presenter: MainPresenterProtocol?

    @IBOutlet weak var activityNameLabel: UILabel!
    @IBOutlet weak var dateLabel: UILabel!
    @IBOutlet weak var confidentLabel: UILabel!
    @IBOutlet weak var gpsSpeedLabel: UILabel!
    @IBOutlet weak var latAndLngLabel: UILabel!
    @IBOutlet weak var locationLabel: UILabel!
    @IBOutlet weak var collectionView: UICollectionView!
    
    var activityFecthData = [ActivityForm]()
    var font = UIFont.systemFont(ofSize: 17)
    var activityData: String?
    var dateData: String?
    var confidentData: String?
    var speedData: Double?
    var locationData: String?
    
    override func viewDidLoad() {
        self.presenter?.notifyViewDidLoad()
        super.viewDidLoad()
        self.initUI()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.presenter?.notifyLocationFetched()
    }
    
    func initUI() {
        self.setupNavigationBar()
        let nibActivityCell = UINib(nibName: "MainCell", bundle: nil)
        self.collectionView.register(nibActivityCell, forCellWithReuseIdentifier: "MainCell")
        self.collectionView.register(UINib.init(nibName: "MainHeader", bundle: Bundle.main), forSupplementaryViewOfKind: UICollectionView.elementKindSectionHeader, withReuseIdentifier: "header")
    }
    
    func setupNavigationBar() {
        self.navigationItem.title = "Significant Change Location"
    }
    
//    func prepareInsertHistoryActivity() {
//        if let activity = self.activityData,
//           let date = self.dateData,
//           let confident =  self.confidentData,
//           let speed = self.speedData,
//           let location = self.locationData {
//                let activityForm = ActivityForm(activity: activity,
//                                                date: date,
//                                                confident: confident,
//                                                speed: speed,
//                                                location: location)
//
//                self.presenter?.notifyInsertHistoryActivity(activity: activityForm)
//            }
//        self.presenter?.selfFetchActivity()
//        self.collectionView.reloadData()
//    }
}

extension MainViewController:  MainViewProtocol {
    
    //MARK: location not show and save
    func displayLocationView(location: String) {
        print("isShowLocationData")
        self.locationLabel.text = "ตำเเหน่งปัจจุบัน\n" + location
        self.locationData = location
    }
    
    func displayGpsSpeed(speed: Double) {
        self.gpsSpeedLabel.text = String(format: "ความเร็ว = %.1f", speed) + " Km/h"
        self.speedData = speed
    }
    
    func displayMotionData(date: String, activity: String) {
        //MARK: การเช็คเปลี่ยนกิจกรรมยังไม่เสรียถ เเละยังเก็บเบื้องหลังไม่ได้
        if activity != activityData {
            self.collectionView.reloadData()
            //self.prepareInsertHistoryActivity()
        } else {
            self.collectionView.reloadData()
            print("activity not change = not insert to database")
        }
        
        self.dateLabel.text = "วันที่เริ่ม = \(date)"
        self.activityNameLabel.text = activity
        
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.2) {
            self.dateData = date
            self.activityData = activity
        }
    }
    
    func displayConfidentActivity(confident: String) {
        self.confidentLabel.text = "ความเเม่นยำ = \(confident)"
        self.confidentData = confident
    }
    
    func displayActivityFetch(activity: [ActivityForm]) {
        self.activityFecthData = activity
    }
}
