//
//  MainInteractor.swift
//  significant-change-location-service
//
//  Created phattarapon on 27/7/2565 BE.
//  Copyright © 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import MapKit
import CoreLocation
import CoreMotion

class MainInteractor {

    weak var presenter: MainPresenterProtocol?
}

extension MainInteractor: MainInteractorProtocol {
    
    func addLocationObserver() {
        NotificationCenter.default.addObserver(self, selector: #selector(onLocationGPSUpdatedNotification(notification:)), name: .LocationHelperDidUpdatedGPSLocation, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(onLocationNotificationError(notification:)), name: .LocationHelperDidError, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(onActivityMotionNotificationUpdated(notification:)), name: .ActivityMotionHelper, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(onSpeedLocationNotificationUpdated(notification:)), name: .LocationSpeedHelperDidUpdatedSelectedLocation, object: nil)
    }
    
    @objc func onLocationGPSUpdatedNotification(notification: Notification) {
        if let location = notification.object as? CLLocation {
            print("location = \(location.coordinate.latitude), \(location.coordinate.longitude)")
            
            var latLng = "\(location.coordinate.latitude), \(location.coordinate.longitude)"
            self.presenter?.notifyDisplayLatLng(latLng: latLng)
        }
    }
    
    @objc func onLocationNotificationError(notification: Notification) {
        if let err = notification.object as? Error {
            print("Location error = \(err)")
        }
    }
    
    @objc func onActivityMotionNotificationUpdated(notification: Notification) {
        if let motion = notification.object as? CMMotionActivity {
            let dateFormatter = DateFormatter()
            dateFormatter.dateFormat = "yyyy-MM-dd HH:mm"
            let date = dateFormatter.string(from: motion.startDate)
            self.presenter?.notifyDisplayMotionData(motion: motion, date: date)
        }
    }
    
    @objc func onSpeedLocationNotificationUpdated(notification: Notification) {
        if let speed = notification.object as? Double {
            self.presenter?.notifyDisplayGPSSpeed(speed: speed)
        }
    }

    func fetchHistoryActivity() {
        let activity = DBActivityHelper().selectActivityData()
        self.presenter?.notifyFetchHistoryActivity(activity: activity)
    }
    
    func insertHistoryActivity(activity: ActivityForm) {
        DBActivityHelper.insertActivity(historyActivity: activity)
    }
}
